### ISSUE TITLE
text location

### ISSUE THREAD

**Issue by sourekv** [rmcgirr83/requirereason#1]
Would you be so kind to locate warning in the proximity of required field?

![image](https://github.com/rmcgirr83/requirereason/assets/48099959/0e266514-33a8-419c-a718-76c7042af0b5)

Thanks for considering that. However I am not sure that is even possible. 
Vlada

**Comment by rmcgirr83** [comment]
Not possible as of now due to no events in that location for phpBB3.

**Comment by sourekv** [comment]
Thanks
